language: php

php:
  - 7.2

services:
  - docker

before_install:
  - composer self-update
  - composer clear-cache
  - composer update --no-interaction --no-ansi --no-suggest --optimize-autoloader --prefer-stable

script:
  - composer install
  - phpunit --configuration tests/unittests/phpunit.xml tests/unittests
