language: php
sudo: required

services:
  - docker

before_install:
- docker pull epcallan/php7-testing-phpunit:7.1-phpunit6
- docker run epcallan/php7-testing-phpunit /bin/sh -c "cd /root/php7-testing-phpunit; bundle exec rake test"

script:
  - composer install
  - phpunit --configuration tests/unittests/phpunit.xml